version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/src/api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
