repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
        exclude: deployment/
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: flake8
        name: Flake8
        description: This hook runs flake8 within our project's environment.
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true
