services:

  abandonauth:
    network_mode: "host"
    build:
      context: src/api
      dockerfile: Dockerfile
      args: # Enables hot reloading
        - uvicorn_extras=--reload
    env_file:
      - ".env"
    depends_on:
      - database
    volumes:  # mount the source code as a volume, so we can use hot reloading
      - "./src/api/abandonauth:/app/abandonauth:ro"
      - "./prisma:/app/prisma:ro"

  website:
    network_mode: "host"
    build:
      context: ./src/website
      dockerfile: Dockerfile
      args:
        ABANDON_AUTH_URL: ${ABANDON_AUTH_URL}
        ABANDON_AUTH_DEVELOPER_APP_ID: ${ABANDON_AUTH_DEVELOPER_APP_ID}
        GITHUB_REDIRECT: ${GITHUB_REDIRECT}
        DISCORD_REDIRECT: ${DISCORD_REDIRECT}

  database:
    image: "postgres:${POSTGRES_VERSION:-15-alpine}"
    network_mode: "host"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 1s
      retries: 5
    environment:
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"

volumes:
  postgres_data:
