version: "3"

services:

  keydb:
    image: eqalpha/keydb
    container_name: keydb
    command: keydb-server /etc/keydb/redis.conf --server-threads 2
    volumes:
      - keydb-storage:/data
    ports:
      - "6379:6379"

volumes:
  keydb-storage:
