version: "3"

services:

  abandonauth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - uvicorn_extras=--reload
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app:ro"

  database:
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 1s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"

volumes:
  postgres_data:
