repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
        exclude: deployment/
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: ruff-lint
        name: ruff linting
        description: Run ruff linting
        entry: poetry run ruff check --force-exclude
        language: system
        'types_or': [python, pyi]
        require_serial: true
        args: [--fix, --exit-non-zero-on-fix]

    -   id: prisma-format
        name: Prisma Format
        description: Run prisma formatter on schema
        entry: poetry run prisma format
        language: system
        types: [python]
        require_serial: true

    -   id: prisma-generate
        name: Prisma Generate
        description: Generate Prisma client before static analysis (pyright)
        entry: poetry run prisma generate --schema prisma/schema.prisma
        language: system
        types: [python]
        require_serial: true

    -   id: pyright
        name: Pyright
        description: Run pyright static analysis
        entry: poetry run pyright
        language: system
        types: [python]
        require_serial: true
