name: Build Frontend

on:
  workflow_call:
    inputs:
      latest:
        description: "If the container should be tagged as latest."
        type: boolean
        required: false
        default: false
      push:
        description: "If the built container should be pushed."
        type: boolean
        required: false
        default: false

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: src/website
          build-args: |
            ABANDON_AUTH_URL=https://auth.abandontech.cloud
            ABANDON_AUTH_DEVELOPER_APP_ID=cd022be1-35af-4248-8d70-4205ed1c20c6
            GITHUB_REDIRECT=https://github.com/login/oauth/authorize?client_id=e2e4eac6e97af84d9f69&redirect_uri=https://auth.abandontech.cloud/api/ui/github-callback&scope=user:email
            DISCORD_REDIRECT=https://discord.com/api/oauth2/authorize?client_id=1002632179794329630&redirect_uri=https%3A%2F%2Fauth.abandontech.cloud%2Fapi%2Fui%2Fdiscord-callback&response_type=code&scope=identify
          push: ${{ inputs.push }}
          tags: |
            ghcr.io/abandontech/abandonauth-frontend:${{ steps.sha_tag.outputs.tag }}
            ${{ inputs.latest && 'ghcr.io/abandontech/abandonauth-frontend:latest' || '' }}
