name: Build Api

on:
  workflow_call:
    inputs:
      latest:
        description: "If the container should be tagged as latest."
        type: boolean
        required: false
        default: false
      push:
        description: "If the built container should be pushed."
        type: boolean
        required: false
        default: false

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: src/api
          push: ${{ inputs.push }}
          tags: |
            ghcr.io/abandontech/abandonauth-api:${{ steps.sha_tag.outputs.tag }}
            ${{ inputs.latest && 'ghcr.io/abandontech/abandonauth-api:latest' || '' }}
