name: Lint & Build Image

on:
  push:
    branches:
      - '!main' # Exclude main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: poetry run flake8

  build:
    runs-on: ubuntu-latest
    needs: [ lint ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get short commit sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push image
        id: build_and_push_docker_image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: BUILD_VERSION=${{ steps.vars.outputs.sha_short }}-dev
          push: true
          tags: |
            registry.abandontech.cloud/abandontech/abandonauth:${{ github.sha }}

      - name: Image digest
        run: |
          echo ${{ steps.build_and_push_docker_image.outputs.digest }}
