name: Main

on:
  push:
    branches: main

jobs:
  linting:
    uses: ./.github/workflows/linting.yml

  build_api:
    uses: ./.github/workflows/build_api.yml
    needs:
      - linting
    with:
      latest: true
      push: true

  build_frontend:
    uses: ./.github/workflows/build_frontend.yml
    needs:
      - linting
    with:
      latest: true
      push: true
