name: Build and Deploy Production

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Tag Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and push image
        id: build_and_push_docker_image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: BUILD_VERSION=${{ env.RELEASE_VERSION }}
          push: true
          tags: |
            registry.abandontech.cloud/abandontech/abandonauth:${{ github.sha }}
            registry.abandontech.cloud/abandontech/abandonauth:${{ env.RELEASE_VERSION }}
            registry.abandontech.cloud/abandontech/abandonauth:latest

      - name: Image digest
        run: |
          echo ${{ steps.build_and_push_docker_image.outputs.digest }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: [ build-production ]
    environment:
      name: Production
      url: https://auth.abandontech.cloud

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy manifest
        uses: actions-hub/kubectl@v1.24.0
        env:
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        with:
          args: apply -f deployment/production-deployment.yml

      - name: Force redeploy
        uses: actions-hub/kubectl@v1.24.0
        env:
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        with:
          args: rollout --namespace=abandontech restart deploy abandonauth
