name: Pull Request

on:
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    uses: ./.github/workflows/linting.yml

  build_api:
    uses: ./.github/workflows/build_api.yml
    needs:
      - linting

  build_frontend:
    uses: ./.github/workflows/build_frontend.yml
      needs:
        - linting
