name: Pull Request

on:
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    uses: ./.github/workflows/linting.yml

  build-deploy:
    uses: ./.github/workflows/build.yml
    needs:
      - linting
